### ISSUE TITLE
wildcard permission found in trie short circuits too early

### ISSUE THREAD

**Issue by bennettellis** [entrecode/shiro-trie#118]
Seems to be a major bug in the way that Shiro-Trie is handling wildcards in the middle of the permission.
Per Apache Shiro design, something like:
`printer:*:lp7200` is a valid permission. 

See doc mentioning wildcard here: 
https://shiro.apache.org/permissions.html

However, according to the documentation, this does NOT mean that the user has ALL on ALL, as for example `"printer:*:*"` It simply means that the user has all of the middle layer on the printer lp7200. Assume that the middle layer is action, as with most implementations, it's not valid to assume that `"printer:*:lp7200"` is equivalent to `"printer:*:*"` aka all actions on all printers. It simply means that the user has all actions on the lp7200 printer.

In our case, the wildcard permission looks like, `"events:*:123"`

However when Shiro-Trie checks permissions based on something like `"events:view:?"`, it returns `"*"` incorrectly.

This code, however:
```
function _permissions(trie, array) {
  var current, results;
  if (!trie || !array ||
    typeof trie !== 'object' || !Array.isArray(array) ||
    Object.keys(trie).length < 1 || array.length < 1) {
    // for recursion safety, we make sure we have really valid values
    return [];
  }
  array = [].concat(array);
  // if we have a star permission, we can just return that
  if (trie.hasOwnProperty('*')) {
    return ['*'];    // <<--- THIS IS THE ERRANT CODE
  }
...
```
is causing the permission check to be short-circuited as soon as it encounters the first `"*"` wildcard in a permission having matched so far. In our case, as soon as it sees "events:*" in the permission `"events:*:123"` it returns `"*"` when we're checking for `"events:view:?"`, thereby telling the calling code that the user has view rights on ALL events, which is incorrect. This seems very contrary to the Shrio Java implementations, where an `"events:*:123"` explicitly means that a user has all rights on event 123, but does not have all rights on any other event. 

To be clear, what we're trying to do here is get all the permissions the users has that match `events:view:?` which should IMHO return `123` when the user has permission `events:*:123` but instead is returning `*`

**Comment by simon-scherzinger** [comment]
Hey 	bennettellis,

thanks for pointin that out.

I had to add some lines to your fix since it was breaking other test cases for tries with something like `"a:*"`. In such a case the granted permission would be `"a:*:*"`, querying this with `"a:?"` must result in `"*"`.

Another solution to your specific case would have been querying with `"events:$:?"`, I believe.

Take care,

Simon

**Comment by bennettellis** [comment]
Thanks for fixing and releasing so quickly!

**Comment by bennettellis** [comment]
This release (0.4.3) doesn't appear to be available on npm. If possible, can you please publish that version? Thanks!

**Comment by bennettellis** [comment]
oh, actually now I see it. Thanks!
