### ISSUE TITLE
How this library persists data ?

### ISSUE THREAD

**Issue by nitishmakhija** [entrecode/shiro-trie#146]
Hi,
Wonderful library for permission management.

Can we store this data onto a database?

**Comment by deyhle** [comment]
This library does not persist the data, it is all in-memory.
You can simply store the permission strings in any database you want, and build the permission-trie out of those strings on runtime.

**Comment by nitishmakhija** [comment]
Thank you for a quick reply,

So that brings another question to my mind even if I do that and I fetch these permissions at run time and try building these at application startup lets say I have 2000 users currently residing in my database and which are bound to grow do you have suggestions on how to add this to trie?

I cannot see a bulk add method even if there was it is not feasible to fetch all the users at runtime.

Any suggestions ?

**Comment by deyhle** [comment]
We are loading a users' permissions once he is doing a request, it is not that expensive (can be stored right with other user profile information). And to be clear: you have one trie instance for each user. So the flow is:

1. user makes request
2. you load user profile data including permission strings from your database
3. you create a `shiroTrie` instance for the user and add the permissions
4. you can check permissions against that instance
5. after the request, you can either cache the trie instance for that user or throw it away and build it again for the next request.
